name: Metrics Deployment

on:
  push:
    branches:
      - master

jobs:
  publish:

    name: Upload Release
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package

      - name: Verify versioned JAR
        run: test -s ./target/SF_FoxyMachines_Legacy_v1.0.0.jar

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: FoxyMachines
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          file: ./target/SF_FoxyMachines_Legacy_v1.0.0.jar
          releaseNotes: ${{ github.event.head_commit.message }}
